### ISSUE TITLE
speed of vmf sampling on GPU?

### ISSUE THREAD

**Issue by fermat97** [jiacheng-xu/vmf_vae_nlp#9]
Hi, I would like to use your `vmf_batch.py` code, and I am wondering if this can reduce the speed on GPU due to the use of `scipy ` for `_vmf_kld_davidson` since I think they are done on CPU.

**Comment by jiacheng-xu** [comment]
If you are tuning the kappa during the training phase of the model, this may be a problem. Some of the functions from scipy are inevitably slow in the GPU context because they are not implemented and optimized for GPU. However, if you fix the kappa and actually you only need to compute KLD once because it's more or less a constant (still in the loss function tho).

**Comment by fermat97** [comment]
Thank you, I have fixed it beforehand and it is now very fast.
